echo:
    build: .
    ports:
        - "8004:80"
    volumes:
        - /etc/ssl:/etc/ssl
        - /home/jacobi/.gvm/pkgsets/go1.5/global:/gopath
    environment:
        GOPATH: /gopath
    working_dir: /gopath/src/github.com/mikerjacobi/poker/server
    links:
        - mongo
mongo:
    image: mongo
    volumes:
      - ./fixtures:/fixtures
selenium_hub:
  image: selenium/hub
selenium_chrome:
  image: selenium/node-chrome
  links:
    - selenium_hub:hub
pdiff_server:
  image: aeharding/webdrivercss-adminpanel
  ports:
    - "9000:9000"
#dpxdt:
#    image: dpxdt
#    ports:
#        - "8015:5000"
#
